### ISSUE TITLE
Outta Wack SVG's!

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#1]
Hey @thomasjbradley,

I tried making this text an SVG and putting it into my site (like the Shopify.ca/2014) site. Weird things are happening.

For some reason, the pattern disappears! Here's what it looks like in illustrator:

![screen shot 2015-02-19 at 1 57 31 pm](https://cloud.githubusercontent.com/assets/6340292/6273680/4dc153ec-b83f-11e4-8393-952d2c432b4d.png)

And here's what it looks like in my preview (from finder):

![screen shot 2015-02-19 at 1 56 15 pm](https://cloud.githubusercontent.com/assets/6340292/6273653/2081c2ea-b83f-11e4-955b-7caaca6c4ca8.png)

And here's what it looks like in the browser:

![screen shot 2015-02-19 at 1 56 20 pm](https://cloud.githubusercontent.com/assets/6340292/6273657/2d80c374-b83f-11e4-9f48-87bb3559f0b2.png)

**Comment by thomasjbradley** [comment]
Inspecting the SVG code directly I can see why it’s happening and know how to fix it.

At the top of the SVG, there’s a whole bunch of fills, like this:

``` css
.st9 {
   fill: url(#SVGID_1_);
}
```

You can see they all point to something with an ID similar to `#SVGID_1_`. But if we look at the `<pattern>` tag we can see its ID is `New_Pattern_8`.

So, if we replace all those fills with the correct ID, the pattern works.

As to why Illustrator isn’t doing that I'm not sure. Send me the file and I’ll have a look.

**Comment by vivkay** [comment]
I tried it again and it seems to work fine now. Hmm. 

Question though, when I try to export it as an SVG, it won't work. When I export it and set the 'type' to 'covert to outlines' it works fine. Is this ok that it's outlines or does this disable all the SVG-ness? 

This is the ai export dialogue box I'm referring to:

![screen shot 2015-02-20 at 2 30 34 pm](https://cloud.githubusercontent.com/assets/6340292/6308247/98162dc4-b910-11e4-9027-b2e65233d159.png)

Thanks! :D

**Comment by thomasjbradley** [comment]
It should be "outlines". Without setting the font type to outlines your user will have to have the typeface you've used installed on their computer.
Also, "Preserve Illustrator Editing..." should not be checked.

Refer to the documentation here:
https://github.com/algonquindesign/html-css/tree/gh-pages/image-formats#svgs

**Comment by vivkay** [comment]
Okie thanks!!
