### ISSUE TITLE
hovering bucket buttons

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#10]
Hi @thomasjbradley,

I've made a huge mess of my portfolio grid! It's getting warmer but I'm getting confused...

What I want is for each bucket to do this:

Natural state:
- opacity 50%, image partly visible
- overlay text with a background fill, that occupies a thin strip across the center of each bucket (eg. 'website design' 'branding design' 'blah blah design' 'click image' etc.)

Hover state:
- opacity 100%, image whole and clear
- no text or other iinterference with image

What I have right now is close. The opacity is beautiful, the  buckets are linked to my behance. But the overlaid text! Uggh!  

My main causes of grief:
1. I want the text to appear on top of the image, so that it's not dimmed by the opacity. Like on this page: http://www.badassembly.com/work/ The images are dimmed but the text is crisp and bright.
2. I want the text to disappear when you hover over the image. Right now it only disappears when you hover over the text itself. I can't think of the best way to separate the text and image, while keeping them in the same unit though (so that the positioning is in-tact).

I hope this made some sort of sense!

Thank you!!

**Comment by vivkay** [comment]
I'm just reading now about z-index... is this like layering? This seems like it might be the key? Or is that going to get me further in the mud? 

...(just tried putting the z index on but it seems to disable the hover/opacity state)?

...and I also noticed that on the badassembly website they are using display: table. Their grid is blowing my mind though–I'm not quite wrapping my mind around it. :/

**Comment by thomasjbradley** [comment]
_z-index:_

I don’t think you'll need `z-index` for this; it is layering, but your text is layering properly already.

_badassembly grid, display: table:_

I don’t know where they’re using `display: table`, but it’s shown to have accessibility ramifications.
I look at their work grid and it’s using Yahoo Pure, which my grid system is inspired by.

_text/image opacity:_

Have you tried targeting the internal image directly to apply `opacity` instead of the `a` tag itself?
That way you can control what element has the opacity.

**Comment by vivkay** [comment]
Yup! I had the opacity on the wrong level element. Thanks to your Jupiter tutorial I worked out how to get it looking like THIS: (some aesthetic tweaking still to go, but not too shabby for a start I reckon!)

![screen shot 2015-02-21 at 7 42 22 pm](https://cloud.githubusercontent.com/assets/6340292/6316806/f0ff9eba-ba01-11e4-9b6b-33669fa68edc.png)

THANKS A MILL!

**Comment by vivkay** [comment]
@thomasjbradley 

Aha! Getting closer but one thing I'm not sure if it's possible to do...

I want the text to disappear when I hover over any part of the bucket. Thus, hovering over the image will do 2 things:
1. The opacity of the image will go to 100% (currently working)
2. The overlaid text will disappear (currently working BUT only when you hover over the button).

Is it possible to make the text disappear when I hover over it's parent (which is the image)?

Thanks!!! (it's all updated on github so you can see what's happening live!)

**Comment by thomasjbradley** [comment]
It’s definitely possible.
Check out the Jupiter hover box tutorial again, because all the code you need is in there.
Especially look at the hovering text part of the code.

Here’s a leading question to help you:
Should you hovering over the `img` or the `a` tag?

**Comment by vivkay** [comment]
Yup. That was way too easy. AWESOMENESS!!!
:pineapple:
