### ISSUE TITLE
gif sizing sorrows

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#11]
Hi @thomasjbradley, 

I spent a million hours on an after effects tutorial to make this gif, but one of the sites I referenced turned out to have a teeny tiny terrible sizing (which I thought was optimized for web...but it turns out it's just super tiny). 

If you go to the site, you can see the gif happening on the first icon (hover over the giant envelope). Do you have any tips on appropriate comp sizing for gifs like these? I don't want to do the other two icons at the wrong size because I've no idea how to resize them...I think I will have to start this one over again _tear_.

This was the reference for gifs/sizing I was using: http://www.markdubois.info/weblog/2014/02/after-effects-animated-gif/ 

Thanks!

**Comment by thomasjbradley** [comment]
I would say, figure out the largest size that envelope is displayed and make your GIF that size. But the bigger you make the GIF the slower it will be to download.

**Comment by vivkay** [comment]
okie! will try again!
