### ISSUE TITLE
inline nav

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#13]
Hey @thomasjbradley, 

I'm not sure how to get my nav elements to appear inline (that property isn't working). I am using some code from another student Jed's interaction class in first year and though it works ok, I wonder if there's a better way. 

my html has the nav listed in a ul, with each button listed as a li ...

Here's my CSS:

```
.nav-btn,
.nav-btn:link,
.nav-btn:visited {
    height: 1.5rem;
    width: 2.5rem;
    overflow: hidden;
    position: absolute;
    top: 1rem;
    left: 5%;
    background: transparent url("../images/hamburger.svg") no-repeat 0 0;
    text-indent: 100%;
    white-space: nowrap;
}

.nav-top {
    max-height: 0; 
    background-color: #000033;
    overflow:hidden;
    -moz-transition: all 250ms linear;
    -o-transition: all 250ms linear;
    -webkit-transition: all 250ms linear;
    transition: all 250ms linear;
}

.nav-top[data-state="expanded"] {
    max-height: 12rem;
}

.nav-top ul { 
    margin: 0;
    padding: 4rem 0;
    list-style-type: none;
}

.nav-top a,
.nav-top a:link,
.nav-top a:visited {
    display: block;
    font-size: 1rem;
    padding: .5rem 5%;
    color: white;
    text-decoration: none;
    display: inline;
}

```

I tried adding this:

```
.nav li {
    display: inline;
}
```

But no dice. Any ideas on how to get them inline? Also, can I get my social media icons up there somehow like in that site you sent me as a reference? I'd have to put some sort of grid inside that top nav bit I suspect...

THANKS!

**Comment by thomasjbradley** [comment]
Double check your class names in that second piece of code you wrote above.

**Comment by vivkay** [comment]
A silly mistake! Works like an inline charm now.

Getting closer. Needs some media queries at the smaller sizes, but at least it's on it's way! :+1: 

![screen shot 2015-02-22 at 8 50 28 pm](https://cloud.githubusercontent.com/assets/6340292/6321814/8e39f464-bad4-11e4-95a6-3429989188d7.png)
