### ISSUE TITLE
validation question - borders

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#14]
@thomasjbradley

Hi Thomas, is this a css validation error I should worry about? If so, what's the work-around? I like how it's working now (with the same colour/2px border). Do I need to resize the button in it's hover state if I want to keep the same effect?

![screen shot 2015-02-22 at 9 27 05 pm](https://cloud.githubusercontent.com/assets/6340292/6322021/af6c74f4-bad9-11e4-892e-eb50ee0ab11b.png)

Thanks!

**Comment by thomasjbradley** [comment]
Is that a warning or an error? If it’s just a warning, I’d ignore it.

**Comment by vivkay** [comment]
okie
