### ISSUE TITLE
connect to url

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#15]
Hi @thomasjbradley, 

I just want to double check something with you – after I connect my code to my domain (vivkay.com) using github as a host/server, will I still be able to access it through github and make changes to it?

Seems like a silly question but I just wanted to double check if I should wait till the last minute to connect it, or if I can do it now and keep working on it.

Thanks!!

**Comment by thomasjbradley** [comment]
After you connect your domain, nothing changes from a GitHub workflow point of view.
The only difference is that the `vivkay.github.io/portfolio` URL stops functioning and redirects to your domain instead.

You can wait until last minute, but not immediate last minute. You need to do it at least a day before to allow the DNS system to propagate the world.

**Comment by vivkay** [comment]
It's A-LIVEEEEE!!! vivkay.com
