### ISSUE TITLE
elusive margins

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#16]
Hi @thomasjbradley, 

I gave up on the opacity hovering, I spent way too long trying alternatives but I guess I don't get it!

For right now, I just want to:
1. fix this pesky margin that's coming apparently from my 'portfolio-tint' class...but I'm so confused as to how to fix this. Margin-bottom: 0 causes more problems. 
2. my last bucket is a different size but I saved it for web the same as the others...I'm not sure how to re-save it to be the same size (when it's compressed). Any ideas?

Thanks!

V

**Comment by thomasjbradley** [comment]
_For the margin:_

Three things:
1. The paragraph has a margin on it that needs to disappear
2. Set `display: block` to the image tags
3. Set `display: block` to the `a` tags

---

_Last bucket:_

The image is different dimensions.

**Comment by vivkay** [comment]
ahh bless you! I wouldn't have ever figured this out on my own!!!
