### ISSUE TITLE
weird alignment

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#17]
hi @thomasjbradley, 

I fixed the svg issue on my name (it hadn't coverted to outline), but realized I want it to be a png because of transparency. So now it looks good BUT I can't get the darn thing to align center. 

I tried margin 0 and auto. I tried text-align as center, I looked at it's parent elements, I inspected in chrome...I can't see what's pushing it left. I can force it center with a margin-right property, but I'd rather have it be auto as that's more precise.

any ideas why this isn't working?

Thanks!

V

**Comment by thomasjbradley** [comment]
Why do you need a PNG for transparency? SVGs can are transparent by default.
