### ISSUE TITLE
fun with GIFs!

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#2]
Hey @thomasjbradley, 

Am struggling with gifs...am not really sure what I'm doing here really...hoping you can offer some clarity.

I want to make them work like the icons in giantant.ca

Good:
I have a working gif on my page!

Bad:
I have no clue how I should go about swapping out the static image for the gif, on hover. Here's what I've tried (but the whole image just disappears!

Here's the code I've tried:

HTML:

```
    <div>
        <img src="images/name-01.svg" alt="Vivienne Kay">
    </div>

    <div class="hover-test"></div>

    <div>
        <p>This is the other gif that's NOT a background image</p>
        <img src="images/test2.gif" alt="">
    </div>

    <div>
       <p>Here's an infinitely looping gif</p>
        <img src="images/gif-test.gif" alt="">
    </div>
```

CSS

```
.hover-test {
    background-image: url(../images/test.png);
    background-repeat: no-repeat;
}

.hover-test:hover {
    background-image: url(../images/test2.gif);
    background-repeat: no-repeat;
}
```

Note:
I have included one extra sample of the gif as an image. I could make it loop forever, but I want it to only do that when in the hover state.

Thank yooou!!

**Comment by thomasjbradley** [comment]
Does you `.hover-test` element take any space up on the page?

**Comment by vivkay** [comment]
erm...no it doesn't seem to take up space (I tried adding a background-color and it's still invisible). Why would this happen though? :/

**Comment by thomasjbradley** [comment]
Does the `div` have content inside it?

**Comment by vivkay** [comment]
erm...no. But can't I keep it as an empty 'box' with a class that adds this class with background images? What content would I put inside? An image maybe? :/

**Comment by thomasjbradley** [comment]
If an element doesn't have content inside it, what does it do?
Are there CSS properties you can add to fix that problem?

**Comment by vivkay** [comment]
I added a paragraph and can see that the .hover-test takes up a tiny amount of space. I tried position: absolute and also float:right, but this doesn't seem to change anything. Is this a grid level issue merhaps?

**Comment by vivkay** [comment]
ooo ooo _raises hand_... overflow: hidden!?

**Comment by vivkay** [comment]
I FIGURED IT OUT (sorta)

**Comment by vivkay** [comment]
I'm having some funky positioning happen but I'm going to try and sort it out before I ask more questions! THANK YOU!
