### ISSUE TITLE
timing question

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#3]
@thomasjbradley, is it straight-forward to time animations to appear when scrolling? Like in the shopify.ca/2014 page? It's so smooth and seamliess, but can it be done with CSS? DUM DUM DUMMMMMMMMM!?

**Comment by thomasjbradley** [comment]
Not with CSS alone, no.

Requires lots of Javascript and we’ll be covering that later this term.
But, if you want to skip ahead a bunch of lessons you can check out the tutorials & videos here:
https://github.com/algonquindesign/javascript/tree/master/effects#scrolling-animations

**Comment by vivkay** [comment]
Awesome! I will probably save this for a summer adventure...depending on how my site comes along for now. Thank you!
