### ISSUE TITLE
display-inline not working

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#4]
Hi @thomasjbradley, 

I'm not sure what's going wrong with these gifs. I have failed in fixing them (but I fixed a bunch of other things!)

Basically I want them to display: inline-block. They won't obey...so I tried positioning them as absolute, and that didn't help either. I have them in a grid and the units are each set to 1-3 (third) so I'm not sure why they're still stacking?

Any ideas?

Here's a screenshot of what's happening. I can see with the inspector that the element is taking up a whole row, but I've really no idea why it's behaving like that.

![screen shot 2015-02-20 at 3 55 27 pm](https://cloud.githubusercontent.com/assets/6340292/6309215/0142b3f0-b919-11e4-9ff2-467c5dc36c54.png)

**Comment by vivkay** [comment]
If it helps, here's what's happening in the site's CSS world: (same content, named differently only because they are placeholders for the three icon/gifs I will be creating).

```
.icon-portfolio {
    background-image: url(../images/test.png);
    background-repeat: no-repeat;
    color: red;
    background-color: red;
    overflow: hidden;
    width: 100%;
    height: 15em;
    display: inline-block;
}

.icon-portfolio:hover {
    background-image: url(../images/gif-test.gif);
    background-repeat: no-repeat;
}

.icon-blog {
    background-image: url(../images/test.png);
    background-repeat: no-repeat;
    color: red;
    background-color: red;
    overflow: hidden;
    width: 100%;
    height: 15em;
    display: inline-block;
}

.icon-blog:hover {
    background-image: url(../images/gif-test.gif);
    background-repeat: no-repeat;
}

.icon-cv {
    background-image: url(../images/test.png);
    background-repeat: no-repeat;
    color: red;
    background-color: red;
    overflow: hidden;
    width: 100%;
    height: 15em;
    display: inline-block;
}

.icon-cv:hover {
    background-image: url(../images/gif-test.gif);
    background-repeat: no-repeat;
}
```

And in HTML land:

```
        <div class="grid">
            <div class="unit unit-xs-1-3 unit-s-1-3 unit-m-1-3 unit-l-1-3 icon-portfolio">
                <p>testing with content</p>
            </div>
            <div class="unit unit-xs-1-3 unit-s-1-3 unit-m-1-3 unit-l-1-3 icon-blog">
                <p>testing with content</p>
            </div>
            <div class="unit unit-xs-1-3 unit-s-1-3 unit-m-1-3 unit-l-1-3 icon-cv">
                <p>testing with content</p>
            </div>
        </div>
```

**Comment by vivkay** [comment]
AAANnnnnnnddd I just fixed it. Woohoo, my brain still sorta works! 

They shouldn't have been in the first div level element. I modified them so that:

```
            <div class="unit unit-xs-1-3 unit-s-1-3 unit-m-1-3 unit-l-1-3">
                <div class="icon-cv"></div>
                <p>testing with content</p>
            </div>
```

She shoots! She scores!!!

**Comment by thomasjbradley** [comment]
:+1:
