### ISSUE TITLE
wacky billboard action!

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#5]
Hi @thomasjbradley!

My billboard looks loverrrly at full size (I'll fix the extra spacing...but it's basically what I want):

![screen shot 2015-02-20 at 3 59 37 pm](https://cloud.githubusercontent.com/assets/6340292/6309301/e6c6a83c-b919-11e4-8a1d-b6457bb246d7.png)

But then at a mobile size, this funkiness happens!

![screen shot 2015-02-20 at 3 59 43 pm](https://cloud.githubusercontent.com/assets/6340292/6309299/de66e8be-b919-11e4-9048-92f2f07795c1.png)
1. I made the background colour black just in-case the image doesn't load (so the white text will always be readable). But why can I suddenly see the black ground at the small size? 
2. I'm perplexed as to why my call to action button is suddenly sticking to the left? I tried searching my code for why this is happening but am stumped. Any ideas?

**Comment by thomasjbradley** [comment]
For the button, double check your unit sizes on the `div`—there's a couple typos.

For the image, you have `background-size: 100%`; what do you want it to do? Fill the whole space?
Plus, instead of black background, why not choose a colour that's more similar to the image itself?

**Comment by vivkay** [comment]
Hmm, I want the billboard to appear full size always (like in the top screenshot above). When I take off the background size, it's responding well except that it's huge. I used your recommendation/tutorial for sizing in photoshop, but it actually made my image even bigger...

![screen shot 2015-02-20 at 5 04 32 pm](https://cloud.githubusercontent.com/assets/6340292/6310245/ecbb68c8-b922-11e4-9580-99c71b52f744.png)

What's the best way to size this thing? Or alternatively, is there a way to keep background-size:100% (since that looks great at the large size), but make it look the same at a small size?

**Comment by thomasjbradley** [comment]
What about `background-size: cover`?

**Comment by vivkay** [comment]
YAYYYYYYYYYYY! :hamster:
