### ISSUE TITLE
hide-and-seek gifs!

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#6]
hey @thomasjbradley, 

These gifs are working how I want in almost every way! My main concern right now is that when the screen gets smaller, the gifs seem to be hidden behind the invisible borders of their div.

Can you see what the problem is? Is there a way around this? :dancer:  ->(that's an icon of a dancer going around the issue…)

![screen shot 2015-02-20 at 5 07 41 pm](https://cloud.githubusercontent.com/assets/6340292/6310311/90be190c-b923-11e4-9a28-d686b8ea4a7a.png)

![screen shot 2015-02-20 at 5 07 50 pm](https://cloud.githubusercontent.com/assets/6340292/6310314/990daf64-b923-11e4-9527-45a9becf647b.png)

**Comment by thomasjbradley** [comment]
Have you tried `background-size`?

**Comment by vivkay** [comment]
and THAT is why you are a wizard. Fixed! Thank you!
