### ISSUE TITLE
portfolio possibilities

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#7]
Hi @thomasjbradley, 

Is this possible to do with css animations/transitions: http://www.badassembly.com/work/ 

I've got my test boxes for this happening on my page, but my brain's gone a little jelly-like. Do you have any suggestions for helpful tuts for this kinda thing?

Thanks so much!!

v

**Comment by thomasjbradley** [comment]
_You mean the hover states, right?_

Then, yes, definitely possible using only CSS, check out one of my recent videos, it's got some similar ideas:

https://www.youtube.com/watch?v=6LOoKJNbEZI&list=PLWjCJDeWfDdfLCjaTRgCMkl_KNl5cfGlm&index=5

**Comment by vivkay** [comment]
Thanks!
