### ISSUE TITLE
icky hamburger happenings

### ISSUE THREAD

**Issue by vivkay** [vivkay/portfolio#8]
Hey @thomasjbradley,

This looks pretty gross to me...I mean, in hamburger world, this would be a sloppy joe that got hit by a bus and is feeling sad. :hamburger: :cactus: 

Any tips on making this look nicer? One thing would be having them display in-line block, rather than stacked. I'd also like the text colour to change on a hover state. I used some old code from 1st year, but don't really understand all the parts super well, nor how to manipulate how this looks. Any tutorials you suggest?

Thanks!

![screen shot 2015-02-20 at 6 35 37 pm](https://cloud.githubusercontent.com/assets/6340292/6311360/ad554ec6-b92f-11e4-8e47-f5709e9b9469.png)

**Comment by thomasjbradley** [comment]
I think inline would definitely make it much better... possibly even have home start beside the hamburger, so everything is a single line.

I also like the way that this page keeps the hamburger in the same location:
http://www.broads-authority.gov.uk/

**Comment by vivkay** [comment]
Good tip! Their hamburger is lovely–will look at this again.
